name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa

      - name: Run tests
        run: |
          source env/bin/activate
          pytest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup environment variables
        with:
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_USER: ${{ secrets.RDS_USER }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_DB: ${{ secrets.RDS_DB }}

      - name: Deploy fetch with Zappa
        run: |
          source env/bin/activate
          if zappa status fetch; then
            zappa update fetch
          else
            zappa deploy fetch
          fi
      
      - name: Deploy process with Zappa
        run: |
          source env/bin/activate
          if zappa status process; then
            zappa update process
          else
            zappa deploy process
          fi
